# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in latest_stock_price.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21"

gem "webmock", "~> 3.23", ">= 3.23.1"

gem "pry", "~> 0.14", ">= 0.14.2"
